name: Deploy qtbase

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: ['ubuntu-22.04']
        include:
          - runner: 'ubuntu-22.04'
            vcpkg_target_triplet: 'x64-linux'
  
    permissions:
      contents: read
      packages: write
  
    runs-on: ${{ matrix.runner }}

    env:
      VCPKG_TARGET_TRIPLET: ${{ matrix.vcpkg_target_triplet }}
      VCPKG_BINARY_SOURCES: 'clear;'
    
    steps:
    - name: Update ubuntu repository
      if: ${{ matrix.runner == 'ubuntu-22.04' }}
      shell: bash
      run: sudo apt-get update
      
    - name: Install ubuntu icu dependencies
      if: ${{ matrix.runner == 'ubuntu-22.04' }}
      shell: bash
      run: sudo apt-get install autoconf-archive
    
    - name: Install ubuntu qtbase dependencies (documented)
      if: ${{ matrix.runner == 'ubuntu-22.04' }}
      shell: bash
      run: sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev

    - name: Install ubuntu qtbase dependencies (undocumented)
      if: ${{ matrix.runner == 'ubuntu-22.04' }}
      shell: bash
      run: sudo apt-get install libgl1-mesa-dev mesa-common-dev
    
    - name: Install ubuntu Ninja
      if: ${{ matrix.runner == 'ubuntu-22.04' }}
      shell: bash
      run: sudo sudo apt-get install ninja-build
    
    - name: uname
      run: uname -a

    - name: Checkout VCPKG
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Bootstrap VCPKG
      run: |
        cmake -E chdir vcpkg sh bootstrap-vcpkg.sh
        
    - name: Install QtBase
      run: |
        ./vcpkg/vcpkg install --debug 'qtbase[core,concurrent,gui,jpeg,network,openssl,png,sql,sql-sqlite,testlib]'
    
    - name: Archive VCPKG Log Files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.runner }} buildlogs
        path: |
          vcpkg/buildtrees/*/*.txt
          vcpkg/buildtrees/*/*.log
    
    - name: Archive VCPKG Package Content
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.runner }} info
        path: |
          vcpkg/installed/vcpkg/info/*